In [2]:
import pandas as pd
from google.colab import drive
import geopandas as gpd
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
ghgrp = pd.read_csv("/content/drive/Shareddrives/EDGI - Shared NEW/12_Environmental_Enforcement_Watch/09_Data/Climate_Data_Project/facility_frsid_metadata.csv")
violations = pd.read_csv("/content/drive/Shareddrives/EDGI - Shared NEW/12_Environmental_Enforcement_Watch/09_Data/Climate_Data_Project/ICIS-AIR_VIOLATION_HISTORY-2023.csv")
frs_links = pd.read_csv("/content/drive/Shareddrives/EDGI - Shared NEW/12_Environmental_Enforcement_Watch/09_Data/Climate_Data_Project/FRS_PROGRAM_LINKS.csv")
coordinates = pd.read_csv("/content/drive/Shareddrives/EDGI - Shared NEW/12_Environmental_Enforcement_Watch/09_Data/Climate_Data_Project/FRS_FACILITIES.csv")

# Join on PGM_SYS_ID
merged = violations.merge(frs_links[["PGM_SYS_ID", "REGISTRY_ID"]],
                          on="PGM_SYS_ID",
                          how="left")

/tmp/ipykernel_3788/2986375734.py:4: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  coordinates = pd.read_csv("/content/drive/Shareddrives/EDGI - Shared NEW/12_Environmental_Enforcement_Watch/09_Data/Climate_Data_Project/FRS_FACILITIES.csv")

In [15]:
# Get list of FRSIDs from ghgrp
ghgrp_ids = ghgrp["FRS Id"].unique()

# Filter merged violations to only those facilities
filtered = merged[merged["REGISTRY_ID"].isin(ghgrp_ids)]

#drop any outside contiguous US (should just be Alaska and Hawaii)
#filtered.drop(filtered[(filtered["STATE_CODE"] == "AK") | (filtered["STATE_CODE"] == "HI")].index, inplace=True)

/tmp/ipykernel_3788/2482281744.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered.drop(filtered[(filtered["STATE_CODE"] == "AK") | (filtered["STATE_CODE"] == "HI")].index, inplace=True)

In [16]:
filtered

,PGM_SYS_ID,ACTIVITY_ID,AGENCY_TYPE_DESC,STATE_CODE,AIR_LCON_CODE,COMP_DETERMINATION_UID,ENF_RESPONSE_POLICY_CODE,PROGRAM_CODES,PROGRAM_DESCS,POLLUTANT_CODES,POLLUTANT_DESCS,EARLIEST_FRV_DETERM_DATE,HPV_DAYZERO_DATE,HPV_RESOLVED_DATE,DSCV_PATHWAY_DATE,NFTC_PATHWAY_DATE,REGISTRY_ID
1,IL000119813AAI,3603596439,State,IL,NaN,IL000AA-2022-00162,FRV,CAASIP CAATVP,State Implementation Plan for National Primary...,300000319 300000320,PARTICULATE MATTER < 10 UM PARTICULATE MATTER ...,02-08-2023,NaN,NaN,NaN,05-09-2023,1.100184e+11
3,IN0000001803300043,3603672177,State,IN,NaN,IN000A101809,HPV,CAATVP,Title V Permits,300000036,Mercury,05-22-2023,08-20-2023,NaN,NaN,NaN,1.100006e+11
9,IN0000001812700085,3603702814,State,IN,NaN,IN000A102513,HPV,CAATVP,Title V Permits,300000018,Hydrochloric acid,05-25-2023,08-23-2023,NaN,07-10-2023,NaN,1.100570e+11
10,IN0000001812700085,3603865992,State,IN,NaN,IN000A109802,HPV,CAATVP,Title V Permits,2092 300000018,HYDROGEN CHLORIDE Hydrochloric acid,12-13-2023,03-12-2024,NaN,01-22-2024,NaN,1.100570e+11
18,OK0000004012300003,3603781497,State,OK,NaN,OK000A4012300003EC0012380,FRV,CAAMACT CAATVP,MACT Standards (40 CFR Part 63) Title V Permits,300000242 300000329,FACIL TOTAL HAZARDOUS AIR POLLUTANTS (HAPS),09-27-2023,NaN,02-06-2025,NaN,NaN,1.100016e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5249,TX0000004824500748,3603677778,State,TX,NaN,TX000A0303580252023206001,FRV,CAATVP,Title V Permits,300000329,FACIL,07-14-2023,NaN,09-05-2024,07-14-2023,NaN,1.100710e+11
5256,NJ00075808,3603791561,State,NJ,NaN,NJ000A104232,FRV,CAASIP CAATVP,State Implementation Plan for National Primary...,NaN,NaN,02-21-2023,NaN,NaN,NaN,NaN,1.100548e+11
5257,NJ00075808,3603831440,State,NJ,NaN,NJ000A106996,FRV,CAASIP CAATVP,State Implementation Plan for National Primary...,NaN,NaN,02-21-2023,NaN,NaN,NaN,NaN,1.100548e+11
5258,NJ00075808,3604362821,State,NJ,NaN,NJ000A127051,FRV,CAASIP CAATVP,State Implementation Plan for National Primary...,NaN,NaN,07-17-2023,NaN,NaN,NaN,NaN,1.100548e+11
5280,CABAAB8136,3603846723,Local,CA,BAA,CABAAA108287,HPV,CAATVP,Title V Permits,300000329,FACIL,11-06-2023,11-06-2023,NaN,NaN,11-06-2023,1.100396e+11

In [ ]:
filtered.to_csv("ghgrp_violations.csv", index=False)

In [ ]:
coordinates_columns = coordinates.columns.tolist()
coordinates_columns

['FAC_NAME',
 'FAC_STREET',
 'FAC_CITY',
 'FAC_STATE',
 'FAC_ZIP',
 'REGISTRY_ID',
 'FAC_COUNTY',
 'FAC_EPA_REGION',
 'LATITUDE_MEASURE',
 'LONGITUDE_MEASURE']

In [ ]:
located = filtered.merge(coordinates[["FAC_NAME", "FAC_STREET", "FAC_CITY", "FAC_STATE", "FAC_COUNTY", "FAC_EPA_REGION", "REGISTRY_ID", "LATITUDE_MEASURE", "LONGITUDE_MEASURE"]],
                          on="REGISTRY_ID",
                          how="left")

In [ ]:
located

,PGM_SYS_ID,ACTIVITY_ID,AGENCY_TYPE_DESC,STATE_CODE,AIR_LCON_CODE,COMP_DETERMINATION_UID,ENF_RESPONSE_POLICY_CODE,PROGRAM_CODES,PROGRAM_DESCS,POLLUTANT_CODES,...,NFTC_PATHWAY_DATE,REGISTRY_ID,FAC_NAME,FAC_STREET,FAC_CITY,FAC_STATE,FAC_COUNTY,FAC_EPA_REGION,LATITUDE_MEASURE,LONGITUDE_MEASURE
0,IL000119813AAI,3603596439,State,IL,NaN,IL000AA-2022-00162,FRV,CAASIP CAATVP,State Implementation Plan for National Primary...,300000319 300000320,...,05-09-2023,1.100184e+11,GRANITE CITY WORKS OF UNITED STATES STEEL CORP,1951 STATE ST,GRANITE CITY,IL,MADISON,5.0,38.695400,-90.136700
1,IN0000001803300043,3603672177,State,IN,NaN,IN000A101809,HPV,CAATVP,Title V Permits,300000036,...,NaN,1.100006e+11,STEEL DYNAMICS INCORPORATED,4500 CO RD 59,BUTLER,IN,DEKALB,5.0,41.370152,-84.921695
2,IN0000001812700085,3603702814,State,IN,NaN,IN000A102513,HPV,CAATVP,Title V Permits,300000018,...,NaN,1.100570e+11,PVS STEEL SERVICES INC,6300 US-12,PORTAGE,IN,PORTER,5.0,41.620389,-87.170278
3,IN0000001812700085,3603865992,State,IN,NaN,IN000A109802,HPV,CAATVP,Title V Permits,2092 300000018,...,NaN,1.100570e+11,PVS STEEL SERVICES INC,6300 US-12,PORTAGE,IN,PORTER,5.0,41.620389,-87.170278
4,OK0000004012300003,3603781497,State,OK,NaN,OK000A4012300003EC0012380,FRV,CAAMACT CAATVP,MACT Standards (40 CFR Part 63) Title V Permits,300000242 300000329,...,NaN,1.100016e+11,HOLCIM US INC/ADA PLT,14500 CO RD 1550,ADA,OK,PONTOTOC,6.0,34.767540,-96.696520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1691,TX0000004824500748,3603677778,State,TX,NaN,TX000A0303580252023206001,FRV,CAATVP,Title V Permits,300000329,...,NaN,1.100710e+11,BAYPORT POLYMERS LLC ETHANE CRACKER,7600 32ND ST,PORT ARTHUR,TX,JEFFERSON,6.0,29.960010,-93.895580
1692,NJ00075808,3603791561,State,NJ,NaN,NJ000A104232,FRV,CAASIP CAATVP,State Implementation Plan for National Primary...,NaN,...,NaN,1.100548e+11,VINELAND CITY MUNICIPAL ELECTRIC UTILITIES CLA...,4087 S LINCOLN AVE,VINELAND,NJ,CUMBERLAND,2.0,39.427370,-75.019470
1693,NJ00075808,3603831440,State,NJ,NaN,NJ000A106996,FRV,CAASIP CAATVP,State Implementation Plan for National Primary...,NaN,...,NaN,1.100548e+11,VINELAND CITY MUNICIPAL ELECTRIC UTILITIES CLA...,4087 S LINCOLN AVE,VINELAND,NJ,CUMBERLAND,2.0,39.427370,-75.019470
1694,NJ00075808,3604362821,State,NJ,NaN,NJ000A127051,FRV,CAASIP CAATVP,State Implementation Plan for National Primary...,NaN,...,NaN,1.100548e+11,VINELAND CITY MUNICIPAL ELECTRIC UTILITIES CLA...,4087 S LINCOLN AVE,VINELAND,NJ,CUMBERLAND,2.0,39.427370,-75.019470
1695,CABAAB8136,3603846723,Local,CA,BAA,CABAAA108287,HPV,CAATVP,Title V Permits,300000329,...,11-06-2023,1.100396e+11,"RUSSELL CITY ENERGY COMPANY, LLC",3862 DEPOT RD,HAYWARD,CA,ALAMEDA,9.0,37.634111,-122.133118

In [ ]:
located.to_csv("ghgrp_caa_violations_2023.csv", index=False)

In [ ]:
ejscreen = gpd.read_file("/content/drive/Shareddrives/EDGI - Shared NEW/12_Environmental_Enforcement_Watch/09_Data/EJScreen_2024_BG_with_AS_CNMI_GU_VI.gdb")

/usr/local/lib/python3.12/dist-packages/pyogrio/geopandas.py:382: UserWarning: More than one layer found in 'EJScreen_2024_BG_with_AS_CNMI_GU_VI.gdb': 'EJSCREEN_Full_with_AS_CNMI_GU_VI' (default), 'USA'. Specify layer parameter to avoid this warning.
  result = read_func(

In [ ]:
ejscreen_columns = ejscreen.columns.tolist()
ejscreen_columns

['ID',
 'STATE_NAME',
 'ST_ABBREV',
 'CNTY_NAME',
 'REGION',
 'ACSTOTPOP',
 'ACSIPOVBAS',
 'ACSEDUCBAS',
 'ACSTOTHH',
 'ACSTOTHU',
 'ACSUNEMPBAS',
 'ACSDISABBAS',
 'DEMOGIDX_2',
 'DEMOGIDX_5',
 'PEOPCOLOR',
 'PEOPCOLORPCT',
 'LOWINCOME',
 'LOWINCPCT',
 'UNEMPLOYED',
 'UNEMPPCT',
 'DISABILITY',
 'DISABILITYPCT',
 'LINGISO',
 'LINGISOPCT',
 'LESSHS',
 'LESSHSPCT',
 'UNDER5',
 'UNDER5PCT',
 'OVER64',
 'OVER64PCT',
 'LIFEEXPPCT',
 'PM25',
 'OZONE',
 'DSLPM',
 'RSEI_AIR',
 'PTRAF',
 'PRE1960',
 'PRE1960PCT',
 'PNPL',
 'PRMP',
 'PTSDF',
 'UST',
 'PWDIS',
 'NO2',
 'DWATER',
 'D2_PM25',
 'D5_PM25',
 'D2_OZONE',
 'D5_OZONE',
 'D2_DSLPM',
 'D5_DSLPM',
 'D2_RSEI_AIR',
 'D5_RSEI_AIR',
 'D2_PTRAF',
 'D5_PTRAF',
 'D2_LDPNT',
 'D5_LDPNT',
 'D2_PNPL',
 'D5_PNPL',
 'D2_PRMP',
 'D5_PRMP',
 'D2_PTSDF',
 'D5_PTSDF',
 'D2_UST',
 'D5_UST',
 'D2_PWDIS',
 'D5_PWDIS',
 'D2_NO2',
 'D5_NO2',
 'D2_DWATER',
 'D5_DWATER',
 'P_DEMOGIDX_2',
 'P_DEMOGIDX_5',
 'P_PEOPCOLORPCT',
 'P_LOWINCPCT',
 'P_UNEMPPCT',
 'P_DISABILITYPCT',
 'P_LINGISOPCT',
 'P_LESSHSPCT',
 'P_UNDER5PCT',
 'P_OVER64PCT',
 'P_LIFEEXPPCT',
 'P_PM25',
 'P_OZONE',
 'P_DSLPM',
 'P_RSEI_AIR',
 'P_PTRAF',
 'P_LDPNT',
 'P_PNPL',
 'P_PRMP',
 'P_PTSDF',
 'P_UST',
 'P_PWDIS',
 'P_NO2',
 'P_DWATER',
 'P_D2_PM25',
 'P_D5_PM25',
 'P_D2_OZONE',
 'P_D5_OZONE',
 'P_D2_DSLPM',
 'P_D5_DSLPM',
 'P_D2_RSEI_AIR',
 'P_D5_RSEI_AIR',
 'P_D2_PTRAF',
 'P_D5_PTRAF',
 'P_D2_LDPNT',
 'P_D5_LDPNT',
 'P_D2_PNPL',
 'P_D5_PNPL',
 'P_D2_PRMP',
 'P_D5_PRMP',
 'P_D2_PTSDF',
 'P_D5_PTSDF',
 'P_D2_UST',
 'P_D5_UST',
 'P_D2_PWDIS',
 'P_D5_PWDIS',
 'P_D2_NO2',
 'P_D5_NO2',
 'P_D2_DWATER',
 'P_D5_DWATER',
 'B_DEMOGIDX_2',
 'B_DEMOGIDX_5',
 'B_PEOPCOLORPCT',
 'B_LOWINCPCT',
 'B_UNEMPPCT',
 'B_DISABILITYPCT',
 'B_LINGISOPCT',
 'B_LESSHSPCT',
 'B_UNDER5PCT',
 'B_OVER64PCT',
 'B_LIFEEXPPCT',
 'B_PM25',
 'B_OZONE',
 'B_DSLPM',
 'B_RSEI_AIR',
 'B_PTRAF',
 'B_LDPNT',
 'B_PNPL',
 'B_PRMP',
 'B_PTSDF',
 'B_UST',
 'B_PWDIS',
 'B_NO2',
 'B_DWATER',
 'B_D2_PM25',
 'B_D5_PM25',
 'B_D2_OZONE',
 'B_D5_OZONE',
 'B_D2_DSLPM',
 'B_D5_DSLPM',
 'B_D2_RSEI_AIR',
 'B_D5_RSEI_AIR',
 'B_D2_PTRAF',
 'B_D5_PTRAF',
 'B_D2_LDPNT',
 'B_D5_LDPNT',
 'B_D2_PNPL',
 'B_D5_PNPL',
 'B_D2_PRMP',
 'B_D5_PRMP',
 'B_D2_PTSDF',
 'B_D5_PTSDF',
 'B_D2_UST',
 'B_D5_UST',
 'B_D2_PWDIS',
 'B_D5_PWDIS',
 'B_D2_NO2',
 'B_D5_NO2',
 'B_D2_DWATER',
 'B_D5_DWATER',
 'T_DEMOGIDX_2',
 'T_DEMOGIDX_5',
 'T_PEOPCOLORPCT',
 'T_LOWINCPCT',
 'T_UNEMPPCT',
 'T_DISABILITYPCT',
 'T_LINGISOPCT',
 'T_LESSHSPCT',
 'T_UNDER5PCT',
 'T_OVER64PCT',
 'T_LIFEEXPPCT',
 'T_PM25',
 'T_OZONE',
 'T_DSLPM',
 'T_RSEI_AIR',
 'T_PTRAF',
 'T_LDPNT',
 'T_PNPL',
 'T_PRMP',
 'T_PTSDF',
 'T_UST',
 'T_PWDIS',
 'T_NO2',
 'T_DWATER',
 'T_D2_PM25',
 'T_D5_PM25',
 'T_D2_OZONE',
 'T_D5_OZONE',
 'T_D2_DSLPM',
 'T_D5_DSLPM',
 'T_D2_RSEI_AIR',
 'T_D5_RSEI_AIR',
 'T_D2_PTRAF',
 'T_D5_PTRAF',
 'T_D2_LDPNT',
 'T_D5_LDPNT',
 'T_D2_PNPL',
 'T_D5_PNPL',
 'T_D2_PRMP',
 'T_D5_PRMP',
 'T_D2_PTSDF',
 'T_D5_PTSDF',
 'T_D2_UST',
 'T_D5_UST',
 'T_D2_PWDIS',
 'T_D5_PWDIS',
 'T_D2_NO2',
 'T_D5_NO2',
 'T_D2_DWATER',
 'T_D5_DWATER',
 'AREALAND',
 'AREAWATER',
 'NPL_CNT',
 'TSDF_CNT',
 'EXCEED_COUNT_80',
 'EXCEED_COUNT_80_SUP',
 'DEMOGIDX_2ST',
 'DEMOGIDX_5ST',
 'Shape_Length',
 'Shape_Area',
 'geometry']

In [ ]:
caa_violations = gpd.GeoDataFrame(located, geometry = gpd.points_from_xy(
    x=located['LONGITUDE_MEASURE'], y=located['LATITUDE_MEASURE'], crs=4326)
)
caa_violations.to_crs(crs=4269, inplace=True) # Project to match EJScreen coordinate systems
caa_violations

,PGM_SYS_ID,ACTIVITY_ID,AGENCY_TYPE_DESC,STATE_CODE,AIR_LCON_CODE,COMP_DETERMINATION_UID,ENF_RESPONSE_POLICY_CODE,PROGRAM_CODES,PROGRAM_DESCS,POLLUTANT_CODES,...,REGISTRY_ID,FAC_NAME,FAC_STREET,FAC_CITY,FAC_STATE,FAC_COUNTY,FAC_EPA_REGION,LATITUDE_MEASURE,LONGITUDE_MEASURE,geometry
0,IL000119813AAI,3603596439,State,IL,NaN,IL000AA-2022-00162,FRV,CAASIP CAATVP,State Implementation Plan for National Primary...,300000319 300000320,...,1.100184e+11,GRANITE CITY WORKS OF UNITED STATES STEEL CORP,1951 STATE ST,GRANITE CITY,IL,MADISON,5.0,38.695400,-90.136700,POINT (-90.1367 38.6954)
1,IN0000001803300043,3603672177,State,IN,NaN,IN000A101809,HPV,CAATVP,Title V Permits,300000036,...,1.100006e+11,STEEL DYNAMICS INCORPORATED,4500 CO RD 59,BUTLER,IN,DEKALB,5.0,41.370152,-84.921695,POINT (-84.9217 41.37015)
2,IN0000001812700085,3603702814,State,IN,NaN,IN000A102513,HPV,CAATVP,Title V Permits,300000018,...,1.100570e+11,PVS STEEL SERVICES INC,6300 US-12,PORTAGE,IN,PORTER,5.0,41.620389,-87.170278,POINT (-87.17028 41.62039)
3,IN0000001812700085,3603865992,State,IN,NaN,IN000A109802,HPV,CAATVP,Title V Permits,2092 300000018,...,1.100570e+11,PVS STEEL SERVICES INC,6300 US-12,PORTAGE,IN,PORTER,5.0,41.620389,-87.170278,POINT (-87.17028 41.62039)
4,OK0000004012300003,3603781497,State,OK,NaN,OK000A4012300003EC0012380,FRV,CAAMACT CAATVP,MACT Standards (40 CFR Part 63) Title V Permits,300000242 300000329,...,1.100016e+11,HOLCIM US INC/ADA PLT,14500 CO RD 1550,ADA,OK,PONTOTOC,6.0,34.767540,-96.696520,POINT (-96.69652 34.76754)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1691,TX0000004824500748,3603677778,State,TX,NaN,TX000A0303580252023206001,FRV,CAATVP,Title V Permits,300000329,...,1.100710e+11,BAYPORT POLYMERS LLC ETHANE CRACKER,7600 32ND ST,PORT ARTHUR,TX,JEFFERSON,6.0,29.960010,-93.895580,POINT (-93.89558 29.96001)
1692,NJ00075808,3603791561,State,NJ,NaN,NJ000A104232,FRV,CAASIP CAATVP,State Implementation Plan for National Primary...,NaN,...,1.100548e+11,VINELAND CITY MUNICIPAL ELECTRIC UTILITIES CLA...,4087 S LINCOLN AVE,VINELAND,NJ,CUMBERLAND,2.0,39.427370,-75.019470,POINT (-75.01947 39.42737)
1693,NJ00075808,3603831440,State,NJ,NaN,NJ000A106996,FRV,CAASIP CAATVP,State Implementation Plan for National Primary...,NaN,...,1.100548e+11,VINELAND CITY MUNICIPAL ELECTRIC UTILITIES CLA...,4087 S LINCOLN AVE,VINELAND,NJ,CUMBERLAND,2.0,39.427370,-75.019470,POINT (-75.01947 39.42737)
1694,NJ00075808,3604362821,State,NJ,NaN,NJ000A127051,FRV,CAASIP CAATVP,State Implementation Plan for National Primary...,NaN,...,1.100548e+11,VINELAND CITY MUNICIPAL ELECTRIC UTILITIES CLA...,4087 S LINCOLN AVE,VINELAND,NJ,CUMBERLAND,2.0,39.427370,-75.019470,POINT (-75.01947 39.42737)
1695,CABAAB8136,3603846723,Local,CA,BAA,CABAAA108287,HPV,CAATVP,Title V Permits,300000329,...,1.100396e+11,"RUSSELL CITY ENERGY COMPANY, LLC",3862 DEPOT RD,HAYWARD,CA,ALAMEDA,9.0,37.634111,-122.133118,POINT (-122.13312 37.63411)

In [ ]:
# Spatial join with EJScreen
caa_ejscreen = gpd.sjoin(caa_violations, ejscreen, how="left", predicate='within')
caa_ejscreen

,PGM_SYS_ID,ACTIVITY_ID,AGENCY_TYPE_DESC,STATE_CODE,AIR_LCON_CODE,COMP_DETERMINATION_UID,ENF_RESPONSE_POLICY_CODE,PROGRAM_CODES,PROGRAM_DESCS,POLLUTANT_CODES,...,AREALAND,AREAWATER,NPL_CNT,TSDF_CNT,EXCEED_COUNT_80,EXCEED_COUNT_80_SUP,DEMOGIDX_2ST,DEMOGIDX_5ST,Shape_Length,Shape_Area
0,IL000119813AAI,3603596439,State,IL,NaN,IL000AA-2022-00162,FRV,CAASIP CAATVP,State Implementation Plan for National Primary...,300000319 300000320,...,1686462.0,14502.0,1.0,2.0,12.0,12.0,3.161922,3.126507,0.067540,0.000176
1,IN0000001803300043,3603672177,State,IN,NaN,IN000A101809,HPV,CAATVP,Title V Permits,300000036,...,96250088.0,20256.0,0.0,1.0,0.0,1.0,0.418365,1.519278,0.505011,0.010365
2,IN0000001812700085,3603702814,State,IN,NaN,IN000A102513,HPV,CAATVP,Title V Permits,300000018,...,6272959.0,4154899.0,0.0,4.0,0.0,0.0,0.000000,0.239984,0.145822,0.001127
3,IN0000001812700085,3603865992,State,IN,NaN,IN000A109802,HPV,CAATVP,Title V Permits,2092 300000018,...,6272959.0,4154899.0,0.0,4.0,0.0,0.0,0.000000,0.239984,0.145822,0.001127
4,OK0000004012300003,3603781497,State,OK,NaN,OK000A4012300003EC0012380,FRV,CAAMACT CAATVP,MACT Standards (40 CFR Part 63) Title V Permits,300000242 300000329,...,2210840.0,0.0,0.0,0.0,5.0,5.0,2.932982,2.453760,0.073443,0.000218
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1691,TX0000004824500748,3603677778,State,TX,NaN,TX000A0303580252023206001,FRV,CAATVP,Title V Permits,300000329,...,17613949.0,3154368.0,1.0,2.0,4.0,6.0,1.496658,1.711134,0.229565,0.001941
1692,NJ00075808,3603791561,State,NJ,NaN,NJ000A104232,FRV,CAASIP CAATVP,State Implementation Plan for National Primary...,NaN,...,11163902.0,37058.0,1.0,0.0,0.0,1.0,0.606947,1.112099,0.228046,0.001172
1693,NJ00075808,3603831440,State,NJ,NaN,NJ000A106996,FRV,CAASIP CAATVP,State Implementation Plan for National Primary...,NaN,...,11163902.0,37058.0,1.0,0.0,0.0,1.0,0.606947,1.112099,0.228046,0.001172
1694,NJ00075808,3604362821,State,NJ,NaN,NJ000A127051,FRV,CAASIP CAATVP,State Implementation Plan for National Primary...,NaN,...,11163902.0,37058.0,1.0,0.0,0.0,1.0,0.606947,1.112099,0.228046,0.001172
1695,CABAAB8136,3603846723,Local,CA,BAA,CABAAA108287,HPV,CAATVP,Title V Permits,300000329,...,15633263.0,3014181.0,0.0,10.0,0.0,0.0,0.938555,0.834066,0.222834,0.001904

In [ ]:
air_pollutant_bg = (
    (caa_ejscreen["P_NO2"] > 79) |
    (caa_ejscreen["P_OZONE"] > 79) |
    (caa_ejscreen["P_RSEI_AIR"] > 79) |
    (caa_ejscreen["P_DSLPM"] > 79) |
    (caa_ejscreen["P_PTRAF"] > 79) |
    (caa_ejscreen["P_PM25"] > 79)
)

In [ ]:
air_pollutant_bg.value_counts()

True     1151
False     545
Name: count, dtype: int64